networks:
  local-network:
    external: true
  laravel:  # Rede interna específica do projeto
    driver: bridge

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: always
    container_name: nginx
    ports:
      - 8000:8000
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - php
      - redis
      - queue
    networks:
      - laravel
      - local-network

  php:
    dns:
    - 8.8.8.8  # ? Google DNS
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: always
    networks:
      - laravel
      - local-network

  queue:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: queue
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - horizon
      - redis
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan', 'queue:work']
    networks:
      - laravel
      - local-network

  horizon:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: horizon
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - redis
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan', 'horizon']
    restart: always
    networks:
      - laravel
      - local-network

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    ports:
      - 6380:6379
    networks:
      - laravel
      - local-network

  artisan:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: artisan
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    working_dir: /var/www/html
    profiles: ["artisan"]
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
      - local-network

  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: composer
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${USER:-laravel} #system user
    profiles: ["composer"]
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel
      - local-network

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    profiles: ["node"]
    networks:
      - laravel
      - local-network