networks:
  laravel:  # Rede interna específica do projeto
    driver: bridge

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: always
    container_name: nginx
    ports:
      - "${NGINX_PORT:-8000}:8000"
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - php
      - pgsql
      - redis
      - horizon
      # - queue
    networks:
      - laravel

  php:
    dns:
    - 8.8.8.8  # ? Google DNS
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: php
    ports:
      - "${PHP_PORT:-9000}:9000"
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: always
    networks:
      - laravel
    devices:
      - /dev/dri:/dev/dri 

  # queue:
  #   build:
  #     context: ./docker/php
  #     dockerfile: Dockerfile
  #     args:
  #       - UID=${UID:-1000}
  #       - GID=${GID:-1000}
  #       - USER=${USER:-laravel}
  #   container_name: queue
  #   volumes:
  #     - ./src:/var/www/html
  #     - .env:/var/www/html/.env
  #   depends_on:
  #     - pgsql
  #     - horizon
  #     - redis
  #   restart: always
  #   working_dir: /var/www/html
  #   entrypoint: ['php', '/var/www/html/artisan', 'queue:work']
  #   networks:
  #     - laravel

  horizon:
    build:
      context: ./docker/horizon
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: horizon
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - redis
      - pgsql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan', 'horizon']
    restart: always
    networks:
      - laravel

  pgsql:
    build:
      context: ./docker/pgsql
      dockerfile: Dockerfile
    container_name: pgsql
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}         
      POSTGRES_USER: ${DB_USERNAME}        
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    volumes:
      - ./docker/pgsql/data:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - laravel

  artisan:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: artisan
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - pgsql
    working_dir: /var/www/html
    profiles: ["artisan"]
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel

  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: composer
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${USER:-laravel} #system user
    profiles: ["composer"]
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    profiles: ["node"]
    networks:
      - laravel

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9701"
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./docker/minio/data:/data
    ports:
      - 9700:9700
      - 9701:9701
    networks:
      - laravel
        # networks:
        #     docker-laravel:
        #       ipv4_address: 172.16.238.10
